---
name: 🤖 Add GitHub Members to Root Team (MoJ)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,10,12,14,16 * * 1-5"

permissions: {}

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-add-members-to-root-team.yml
    with:
      organization-name: "ministryofjustice"
      python-version: "3.11"
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      logging-level: ${{ secrets.LOGGING_LEVEL }}
