---
name: Reusable - Python Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        type: string
        default: "3.11"
      run-coverage:
        description: "Whether to upload coverage to Codecov"
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ inputs['python-version'] }}
          cache: "pipenv"

      - name: Install Pipenv
        run: |
          cat <<'EOF' > .pipenv-requirements-ci.txt
          pipenv==2024.4.1 --hash=sha256:ab26ee98a7d83d342c1f562ee0564094ab1de091e5d5cec4eeaa95fb600de998
          EOF
          python -m pip install --require-hashes -r .pipenv-requirements-ci.txt

      - name: Verify Pipfile.lock is in sync
        run: pipenv verify

      - name: Install Dependencies
        run: pipenv sync --dev --verbose

      - name: Run Unit Tests
        run: pipenv run tests

      - name: Show Coverage
        run: pipenv run tests_report

      - name: Upload Coverage to Codecov
        if: inputs['run-coverage']
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v4.6.0
